server:
  port: 8000

spring:
  # datasource
  datasource:
    ams:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: '1234567890.'
      url: jdbc:mysql://localhost:3306/healthman_test?serverTimezone=Asia/Shanghai
    mjms:
      driver-class-name: dm.jdbc.driver.DmDriver
      username: VHR
      password: '1234567890.'
      url: jdbc:dm://localhost:5237/vhr
  # jackson
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:SS
    time-zone: GMT+8
  # http file
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB
      resolve-lazily: true
  # default false
  #  main:
  #    allow-circular-references: false
  # mybatis
mybatis:
  ams:
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      use-generated-keys: true
      jdbc-type-for-null: null
      local-cache-scope: statement
    mapper-locations: classpath:/mapper/ams/*.xml
  mjms:
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      use-generated-keys: true
      jdbc-type-for-null: null
      local-cache-scope: statement
    mapper-locations: classpath:/mapper/mjms/*.xml
#  type-aliases-package: com.rufeng.healthman.pojo
#vhr:
#  work-dir: ${user.home}/.vhr
